# Generated by Django 3.2.4 on 2022-10-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0007_auto_20220722_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
