# Generated by Django 3.2.4 on 2022-10-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0010_auto_20221014_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='latitude',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='film',
            name='longitude',
        ),
    ]
